. "$PSScriptRoot\lib\CGW-Parser.ps1"

# HW + ARR + late patch duty manifest: (id, CGWpage, zhName, expansion, type, playerCount, level, highEnd)
$HW = '3.x 蒼穹的禁城 (Heavensward)'
$ARR = '2.x 重生之境 (A Realm Reborn)'
$DT = '7.x 黃金的遺產 (Dawntrail)'
$EW = '6.x 曉月之終途 (Endwalker)'

$manifest = @(
    # HW dungeons (remaining 14)
    @{Id='aetherochemical_research_facility'; Page='The_Aetherochemical_Research_Facility'; Zh='以太化學研究所'; Exp=$HW; Type='dungeon'; PC=4; Lv=60; HE=$false},
    @{Id='neverreap'; Page='Neverreap'; Zh='天輪之首'; Exp=$HW; Type='dungeon'; PC=4; Lv=60; HE=$false},
    @{Id='fractal_continuum'; Page='The_Fractal_Continuum'; Zh='次元邊境遺跡'; Exp=$HW; Type='dungeon'; PC=4; Lv=60; HE=$false},
    @{Id='sohr_khai'; Page='Sohr_Khai'; Zh='索爾凱'; Exp=$HW; Type='dungeon'; PC=4; Lv=60; HE=$false},
    @{Id='xelphatol'; Page='Xelphatol'; Zh='薩烏塞爾巴塔'; Exp=$HW; Type='dungeon'; PC=4; Lv=60; HE=$false},
    @{Id='antitower'; Page='The_Antitower'; Zh='反塔'; Exp=$HW; Type='dungeon'; PC=4; Lv=60; HE=$false},
    @{Id='baelsars_wall'; Page="Baelsar's_Wall"; Zh='巴埃薩爾長城'; Exp=$HW; Type='dungeon'; PC=4; Lv=60; HE=$false},
    @{Id='sohm_al_hard'; Page='Sohm_Al_(Hard)'; Zh='蘇姆艾爾大山 (零式)'; Exp=$HW; Type='dungeon'; PC=4; Lv=60; HE=$false},
    @{Id='haukke_manor_hard'; Page='Haukke_Manor_(Hard)'; Zh='霍克宅邸 (零式)'; Exp=$HW; Type='dungeon'; PC=4; Lv=50; HE=$false},
    @{Id='lost_city_of_amdapor_hard'; Page='The_Lost_City_of_Amdapor_(Hard)'; Zh='安達普爾失落之都 (零式)'; Exp=$HW; Type='dungeon'; PC=4; Lv=60; HE=$false},
    @{Id='hullbreaker_isle_hard'; Page='Hullbreaker_Isle_(Hard)'; Zh='破船島 (零式)'; Exp=$HW; Type='dungeon'; PC=4; Lv=60; HE=$false},
    @{Id='pharos_sirius_hard'; Page='Pharos_Sirius_(Hard)'; Zh='天狼星燈塔 (零式)'; Exp=$HW; Type='dungeon'; PC=4; Lv=60; HE=$false},
    @{Id='great_gubal_library_hard'; Page='The_Great_Gubal_Library_(Hard)'; Zh='古巴爾大圖書館 (零式)'; Exp=$HW; Type='dungeon'; PC=4; Lv=60; HE=$false},
    @{Id='saint_mociannes_arboretum'; Page="Saint_Mocianne's_Arboretum"; Zh='聖莫西安植物園'; Exp=$HW; Type='dungeon'; PC=4; Lv=60; HE=$false},
    # HW trials
    @{Id='limitless_blue_hard'; Page='The_Limitless_Blue_(Extreme)'; Zh='蒼藍深淵殲滅戰'; Exp=$HW; Type='trial'; PC=8; Lv=60; HE=$false},
    @{Id='limitless_blue_extreme'; Page='The_Limitless_Blue_(Extreme)'; Zh='蒼藍深淵殲殛戰'; Exp=$HW; Type='trial'; PC=8; Lv=60; HE=$true},
    @{Id='thok_ast_thok_hard'; Page='Thok_ast_Thok_(Hard)'; Zh='托克托克殲滅戰'; Exp=$HW; Type='trial'; PC=8; Lv=60; HE=$false},
    @{Id='thok_ast_thok_extreme'; Page='Thok_ast_Thok_(Extreme)'; Zh='托克托克殲殛戰'; Exp=$HW; Type='trial'; PC=8; Lv=60; HE=$true},
    @{Id='singularity_reactor'; Page='The_Singularity_Reactor'; Zh='奇點反應爐'; Exp=$HW; Type='trial'; PC=8; Lv=60; HE=$false},
    @{Id='final_steps_of_faith'; Page='The_Final_Steps_of_Faith'; Zh='信仰的終末'; Exp=$HW; Type='trial'; PC=8; Lv=60; HE=$false},
    @{Id='minstrels_ballad_thordans_reign'; Page="The_Minstrel's_Ballad:_Thordan's_Reign"; Zh='索爾頓王統治絕嘆殲殛戰'; Exp=$HW; Type='trial'; PC=8; Lv=60; HE=$true},
    @{Id='minstrels_ballad_nidhoggs_rage'; Page="The_Minstrel's_Ballad:_Nidhogg's_Rage"; Zh='尼德霍格憤怒絕嘆殲殛戰'; Exp=$HW; Type='trial'; PC=8; Lv=60; HE=$true},
    @{Id='containment_bay_s1t7'; Page='Containment_Bay_S1T7'; Zh='兵器隔離倉 S1T7'; Exp=$HW; Type='trial'; PC=8; Lv=60; HE=$false},
    @{Id='containment_bay_s1t7_extreme'; Page='Containment_Bay_S1T7_(Extreme)'; Zh='兵器隔離倉 S1T7 殲殛戰'; Exp=$HW; Type='trial'; PC=8; Lv=60; HE=$true},
    @{Id='containment_bay_p1t6'; Page='Containment_Bay_P1T6'; Zh='兵器隔離倉 P1T6'; Exp=$HW; Type='trial'; PC=8; Lv=60; HE=$false},
    @{Id='containment_bay_p1t6_extreme'; Page='Containment_Bay_P1T6_(Extreme)'; Zh='兵器隔離倉 P1T6 殲殛戰'; Exp=$HW; Type='trial'; PC=8; Lv=60; HE=$true},
    @{Id='containment_bay_z1t9'; Page='Containment_Bay_Z1T9'; Zh='兵器隔離倉 Z1T9'; Exp=$HW; Type='trial'; PC=8; Lv=60; HE=$false},
    @{Id='containment_bay_z1t9_extreme'; Page='Containment_Bay_Z1T9_(Extreme)'; Zh='兵器隔離倉 Z1T9 殲殛戰'; Exp=$HW; Type='trial'; PC=8; Lv=60; HE=$true},
    # HW alliance
    @{Id='void_ark'; Page='The_Void_Ark'; Zh='虛無方舟'; Exp=$HW; Type='alliance'; PC=24; Lv=60; HE=$false},
    @{Id='weeping_city_of_mhach'; Page='The_Weeping_City_of_Mhach'; Zh='慟哭之都姆哈奇'; Exp=$HW; Type='alliance'; PC=24; Lv=60; HE=$false},
    @{Id='dun_scaith'; Page='Dun_Scaith'; Zh='聖闇的反逆者敦斯凱'; Exp=$HW; Type='alliance'; PC=24; Lv=60; HE=$false},
    # Alexander Normal
    @{Id='alexander_-_the_fist_of_the_father'; Page='Alexander_-_The_Fist_of_the_Father'; Zh='亞歷山大零式 起源之章 1'; Exp=$HW; Type='raid'; PC=8; Lv=60; HE=$false},
    @{Id='alexander_-_the_cuff_of_the_father'; Page='Alexander_-_The_Cuff_of_the_Father'; Zh='亞歷山大零式 起源之章 2'; Exp=$HW; Type='raid'; PC=8; Lv=60; HE=$false},
    @{Id='alexander_-_the_arm_of_the_father'; Page='Alexander_-_The_Arm_of_the_Father'; Zh='亞歷山大零式 起源之章 3'; Exp=$HW; Type='raid'; PC=8; Lv=60; HE=$false},
    @{Id='alexander_-_the_burden_of_the_father'; Page='Alexander_-_The_Burden_of_the_Father'; Zh='亞歷山大零式 起源之章 4'; Exp=$HW; Type='raid'; PC=8; Lv=60; HE=$false},
    @{Id='alexander_-_the_fist_of_the_son'; Page='Alexander_-_The_Fist_of_the_Son'; Zh='亞歷山大零式 律動之章 1'; Exp=$HW; Type='raid'; PC=8; Lv=60; HE=$false},
    @{Id='alexander_-_the_cuff_of_the_son'; Page='Alexander_-_The_Cuff_of_the_Son'; Zh='亞歷山大零式 律動之章 2'; Exp=$HW; Type='raid'; PC=8; Lv=60; HE=$false},
    @{Id='alexander_-_the_arm_of_the_son'; Page='Alexander_-_The_Arm_of_the_Son'; Zh='亞歷山大零式 律動之章 3'; Exp=$HW; Type='raid'; PC=8; Lv=60; HE=$false},
    @{Id='alexander_-_the_burden_of_the_son'; Page='Alexander_-_The_Burden_of_the_Son'; Zh='亞歷山大零式 律動之章 4'; Exp=$HW; Type='raid'; PC=8; Lv=60; HE=$false},
    @{Id='alexander_-_the_eyes_of_the_creator'; Page='Alexander_-_The_Eyes_of_the_Creator'; Zh='亞歷山大零式 天動之章 1'; Exp=$HW; Type='raid'; PC=8; Lv=60; HE=$false},
    @{Id='alexander_-_the_breath_of_the_creator'; Page='Alexander_-_The_Breath_of_the_Creator'; Zh='亞歷山大零式 天動之章 2'; Exp=$HW; Type='raid'; PC=8; Lv=60; HE=$false},
    @{Id='alexander_-_the_heart_of_the_creator'; Page='Alexander_-_The_Heart_of_the_Creator'; Zh='亞歷山大零式 天動之章 3'; Exp=$HW; Type='raid'; PC=8; Lv=60; HE=$false},
    @{Id='alexander_-_the_soul_of_the_creator'; Page='Alexander_-_The_Soul_of_the_Creator'; Zh='亞歷山大零式 天動之章 4'; Exp=$HW; Type='raid'; PC=8; Lv=60; HE=$false},
    # Alexander Savage
    @{Id='alexander_-_the_fist_of_the_father_savage'; Page='Alexander_-_The_Fist_of_the_Father_(Savage)'; Zh='亞歷山大零式 起源之章 1 (零式)'; Exp=$HW; Type='raid'; PC=8; Lv=60; HE=$true},
    @{Id='alexander_-_the_cuff_of_the_father_savage'; Page='Alexander_-_The_Cuff_of_the_Father_(Savage)'; Zh='亞歷山大零式 起源之章 2 (零式)'; Exp=$HW; Type='raid'; PC=8; Lv=60; HE=$true},
    @{Id='alexander_-_the_arm_of_the_father_savage'; Page='Alexander_-_The_Arm_of_the_Father_(Savage)'; Zh='亞歷山大零式 起源之章 3 (零式)'; Exp=$HW; Type='raid'; PC=8; Lv=60; HE=$true},
    @{Id='alexander_-_the_burden_of_the_father_savage'; Page='Alexander_-_The_Burden_of_the_Father_(Savage)'; Zh='亞歷山大零式 起源之章 4 (零式)'; Exp=$HW; Type='raid'; PC=8; Lv=60; HE=$true},
    @{Id='alexander_-_the_fist_of_the_son_savage'; Page='Alexander_-_The_Fist_of_the_Son_(Savage)'; Zh='亞歷山大零式 律動之章 1 (零式)'; Exp=$HW; Type='raid'; PC=8; Lv=60; HE=$true},
    @{Id='alexander_-_the_cuff_of_the_son_savage'; Page='Alexander_-_The_Cuff_of_the_Son_(Savage)'; Zh='亞歷山大零式 律動之章 2 (零式)'; Exp=$HW; Type='raid'; PC=8; Lv=60; HE=$true},
    @{Id='alexander_-_the_arm_of_the_son_savage'; Page='Alexander_-_The_Arm_of_the_Son_(Savage)'; Zh='亞歷山大零式 律動之章 3 (零式)'; Exp=$HW; Type='raid'; PC=8; Lv=60; HE=$true},
    @{Id='alexander_-_the_burden_of_the_son_savage'; Page='Alexander_-_The_Burden_of_the_Son_(Savage)'; Zh='亞歷山大零式 律動之章 4 (零式)'; Exp=$HW; Type='raid'; PC=8; Lv=60; HE=$true},
    @{Id='alexander_-_the_eyes_of_the_creator_savage'; Page='Alexander_-_The_Eyes_of_the_Creator_(Savage)'; Zh='亞歷山大零式 天動之章 1 (零式)'; Exp=$HW; Type='raid'; PC=8; Lv=60; HE=$true},
    @{Id='alexander_-_the_breath_of_the_creator_savage'; Page='Alexander_-_The_Breath_of_the_Creator_(Savage)'; Zh='亞歷山大零式 天動之章 2 (零式)'; Exp=$HW; Type='raid'; PC=8; Lv=60; HE=$true},
    @{Id='alexander_-_the_heart_of_the_creator_savage'; Page='Alexander_-_The_Heart_of_the_Creator_(Savage)'; Zh='亞歷山大零式 天動之章 3 (零式)'; Exp=$HW; Type='raid'; PC=8; Lv=60; HE=$true},
    @{Id='alexander_-_the_soul_of_the_creator_savage'; Page='Alexander_-_The_Soul_of_the_Creator_(Savage)'; Zh='亞歷山大零式 天動之章 4 (零式)'; Exp=$HW; Type='raid'; PC=8; Lv=60; HE=$true},
    # ARR MSQ + side dungeons
    @{Id='sastasha_hard'; Page='Sastasha_(Hard)'; Zh='薩斯塔夏 (零式)'; Exp=$ARR; Type='dungeon'; PC=4; Lv=50; HE=$false},
    @{Id='tamtara_deepcroft'; Page='The_Tam-Tara_Deepcroft'; Zh='坦塔拉墓地'; Exp=$ARR; Type='dungeon'; PC=4; Lv=19; HE=$false},
    @{Id='tamtara_deepcroft_hard'; Page='The_Tam-Tara_Deepcroft_(Hard)'; Zh='坦塔拉墓地 (零式)'; Exp=$ARR; Type='dungeon'; PC=4; Lv=50; HE=$false},
    @{Id='copperbell_mines'; Page='Copperbell_Mines'; Zh='銅鈴銅山'; Exp=$ARR; Type='dungeon'; PC=4; Lv=20; HE=$false},
    @{Id='copperbell_mines_hard'; Page='Copperbell_Mines_(Hard)'; Zh='銅鈴銅山 (零式)'; Exp=$ARR; Type='dungeon'; PC=4; Lv=50; HE=$false},
    @{Id='halatali'; Page='Halatali'; Zh='哈利塔利'; Exp=$ARR; Type='dungeon'; PC=4; Lv=24; HE=$false},
    @{Id='halatali_hard'; Page='Halatali_(Hard)'; Zh='哈利塔利 (零式)'; Exp=$ARR; Type='dungeon'; PC=4; Lv=50; HE=$false},
    @{Id='thousand_maws_of_totorak'; Page='The_Thousand_Maws_of_Toto-Rak'; Zh='托托拉克千獄'; Exp=$ARR; Type='dungeon'; PC=4; Lv=27; HE=$false},
    @{Id='haukke_manor'; Page='Haukke_Manor'; Zh='霍克宅邸'; Exp=$ARR; Type='dungeon'; PC=4; Lv=31; HE=$false},
    @{Id='brayfloxs_longstop'; Page="Brayflox's_Longstop"; Zh='布雷福洛斯長停'; Exp=$ARR; Type='dungeon'; PC=4; Lv=35; HE=$false},
    @{Id='brayfloxs_longstop_hard'; Page="Brayflox's_Longstop_(Hard)"; Zh='布雷福洛斯長停 (零式)'; Exp=$ARR; Type='dungeon'; PC=4; Lv=50; HE=$false},
    @{Id='sunken_temple_of_qarn'; Page='The_Sunken_Temple_of_Qarn'; Zh='卡恩沉沒之廟'; Exp=$ARR; Type='dungeon'; PC=4; Lv=38; HE=$false},
    @{Id='sunken_temple_of_qarn_hard'; Page='The_Sunken_Temple_of_Qarn_(Hard)'; Zh='卡恩沉沒之廟 (零式)'; Exp=$ARR; Type='dungeon'; PC=4; Lv=50; HE=$false},
    @{Id='cutters_cry'; Page="Cutter's_Cry"; Zh='科特之嚎'; Exp=$ARR; Type='dungeon'; PC=4; Lv=41; HE=$false},
    @{Id='stone_vigil'; Page='The_Stone_Vigil'; Zh='石之家'; Exp=$ARR; Type='dungeon'; PC=4; Lv=44; HE=$false},
    @{Id='stone_vigil_hard'; Page='The_Stone_Vigil_(Hard)'; Zh='石之家 (零式)'; Exp=$ARR; Type='dungeon'; PC=4; Lv=50; HE=$false},
    @{Id='dzemael_darkhold'; Page='Dzemael_Darkhold'; Zh='德澤梅亞迷洞'; Exp=$ARR; Type='dungeon'; PC=4; Lv=47; HE=$false},
    @{Id='aurum_vale'; Page='The_Aurum_Vale'; Zh='黃金谷'; Exp=$ARR; Type='dungeon'; PC=4; Lv=49; HE=$false},
    @{Id='wanderers_palace'; Page="The_Wanderer's_Palace"; Zh='流浪者皇宮'; Exp=$ARR; Type='dungeon'; PC=4; Lv=50; HE=$false},
    @{Id='wanderers_palace_hard'; Page="The_Wanderer's_Palace_(Hard)"; Zh='流浪者皇宮 (零式)'; Exp=$ARR; Type='dungeon'; PC=4; Lv=50; HE=$false},
    @{Id='castrum_meridianum'; Page='Castrum_Meridianum'; Zh='皇都梅利提敦'; Exp=$ARR; Type='dungeon'; PC=8; Lv=50; HE=$false},
    @{Id='praetorium'; Page='The_Praetorium'; Zh='帝國禁區'; Exp=$ARR; Type='dungeon'; PC=8; Lv=50; HE=$false},
    @{Id='amdapor_keep'; Page='Amdapor_Keep'; Zh='安達普爾要塞'; Exp=$ARR; Type='dungeon'; PC=4; Lv=50; HE=$false},
    @{Id='amdapor_keep_hard'; Page='Amdapor_Keep_(Hard)'; Zh='安達普爾要塞 (零式)'; Exp=$ARR; Type='dungeon'; PC=4; Lv=50; HE=$false},
    @{Id='pharos_sirius'; Page='Pharos_Sirius'; Zh='天狼星燈塔'; Exp=$ARR; Type='dungeon'; PC=4; Lv=50; HE=$false},
    @{Id='lost_city_of_amdapor'; Page='The_Lost_City_of_Amdapor'; Zh='安達普爾失落之都'; Exp=$ARR; Type='dungeon'; PC=4; Lv=50; HE=$false},
    @{Id='hullbreaker_isle'; Page='Hullbreaker_Isle'; Zh='破船島'; Exp=$ARR; Type='dungeon'; PC=4; Lv=50; HE=$false},
    @{Id='snowcloak'; Page='Snowcloak'; Zh='雪斗篷'; Exp=$ARR; Type='dungeon'; PC=4; Lv=50; HE=$false},
    @{Id='keeper_of_the_lake'; Page='Keeper_of_the_Lake'; Zh='湖之守護者'; Exp=$ARR; Type='dungeon'; PC=4; Lv=50; HE=$false},
    # ARR trials
    @{Id='bowl_of_embers'; Page='The_Navel'; Zh='火光之碗'; Exp=$ARR; Type='trial'; PC=8; Lv=22; HE=$false},
    @{Id='bowl_of_embers_hard'; Page='The_Navel_(Hard)'; Zh='火光之碗 (零式)'; Exp=$ARR; Type='trial'; PC=8; Lv=50; HE=$false},
    @{Id='bowl_of_embers_extreme'; Page='The_Navel_(Extreme)'; Zh='火光之碗 (極式)'; Exp=$ARR; Type='trial'; PC=8; Lv=50; HE=$true},
    @{Id='howling_eye'; Page='The_Navel'; Zh='咆嘯之眼'; Exp=$ARR; Type='trial'; PC=8; Lv=46; HE=$false},
    @{Id='howling_eye_hard'; Page='The_Navel_(Hard)'; Zh='咆嘯之眼 (零式)'; Exp=$ARR; Type='trial'; PC=8; Lv=50; HE=$false},
    @{Id='howling_eye_extreme'; Page='The_Navel_(Extreme)'; Zh='咆嘯之眼 (極式)'; Exp=$ARR; Type='trial'; PC=8; Lv=50; HE=$true},
    @{Id='navel'; Page='The_Navel'; Zh='大地之臍'; Exp=$ARR; Type='trial'; PC=8; Lv=36; HE=$false},
    @{Id='navel_hard'; Page='The_Navel_(Hard)'; Zh='大地之臍 (零式)'; Exp=$ARR; Type='trial'; PC=8; Lv=50; HE=$false},
    @{Id='navel_extreme'; Page='The_Navel_(Extreme)'; Zh='大地之臍 (極式)'; Exp=$ARR; Type='trial'; PC=8; Lv=50; HE=$true},
    @{Id='whorleater_hard'; Page='The_Whorleater_(Hard)'; Zh='海濤戰艦 (零式)'; Exp=$ARR; Type='trial'; PC=8; Lv=50; HE=$false},
    @{Id='whorleater_extreme'; Page='The_Whorleater_(Extreme)'; Zh='海濤戰艦 (極式)'; Exp=$ARR; Type='trial'; PC=8; Lv=50; HE=$true},
    @{Id='striking_tree_hard'; Page='The_Striking_Tree_(Hard)'; Zh='衝擊之樹 (零式)'; Exp=$ARR; Type='trial'; PC=8; Lv=50; HE=$false},
    @{Id='striking_tree_extreme'; Page='The_Striking_Tree_(Extreme)'; Zh='衝擊之樹 (極式)'; Exp=$ARR; Type='trial'; PC=8; Lv=50; HE=$true},
    @{Id='akh_afah_amphitheatre_hard'; Page='Akh_Afah_Amphitheatre_(Hard)'; Zh='永生圓劇場 (零式)'; Exp=$ARR; Type='trial'; PC=8; Lv=50; HE=$false},
    @{Id='akh_afah_amphitheatre_extreme'; Page='Akh_Afah_Amphitheatre_(Extreme)'; Zh='永生圓劇場 (極式)'; Exp=$ARR; Type='trial'; PC=8; Lv=50; HE=$true},
    @{Id='thornmarch_hard'; Page='Thornmarch_(Hard)'; Zh='荊棘進軍 (零式)'; Exp=$ARR; Type='trial'; PC=8; Lv=50; HE=$false},
    @{Id='thornmarch_extreme'; Page='Thornmarch_(Extreme)'; Zh='荊棘進軍 (極式)'; Exp=$ARR; Type='trial'; PC=8; Lv=50; HE=$true},
    @{Id='a_relic_reborn_the_chimera'; Page='A_Relic_Reborn:_The_Chimera'; Zh='奇美拉的重生'; Exp=$ARR; Type='trial'; PC=4; Lv=50; HE=$false},
    @{Id='a_relic_reborn_the_hydra'; Page='A_Relic_Reborn:_The_Hydra'; Zh='海德拉的重生'; Exp=$ARR; Type='trial'; PC=4; Lv=50; HE=$false},
    @{Id='battle_on_the_big_bridge'; Page='Battle_on_the_Big_Bridge'; Zh='大橋之戰'; Exp=$ARR; Type='trial'; PC=8; Lv=50; HE=$false},
    @{Id='battle_in_the_big_keep'; Page='Battle_in_the_Big_Keep'; Zh='大要塞之戰'; Exp=$ARR; Type='trial'; PC=8; Lv=50; HE=$false},
    @{Id='dragons_neck'; Page="The_Dragon's_Neck"; Zh='龍頸要塞'; Exp=$ARR; Type='trial'; PC=8; Lv=50; HE=$false},
    @{Id='chrysalis'; Page='The_Steps_of_Faith'; Zh='蛹'; Exp=$ARR; Type='trial'; PC=8; Lv=50; HE=$false},
    @{Id='urths_fount'; Page="Urth's_Fount"; Zh='大地之泉'; Exp=$ARR; Type='trial'; PC=8; Lv=50; HE=$false},
    @{Id='minstrels_ballad_ultimas_bane'; Page="The_Minstrel's_Ballad:_Ultima's_Bane"; Zh='究極幻神絕嘆殲殛戰'; Exp=$ARR; Type='trial'; PC=8; Lv=50; HE=$true},
    @{Id='porta_decumana'; Page='The_Steps_of_Faith'; Zh='後門帝國禁區'; Exp=$ARR; Type='trial'; PC=8; Lv=50; HE=$false},
    # Coil of Bahamut
    @{Id='binding_coil_of_bahamut_-_turn_1'; Page='The_Binding_Coil_of_Bahamut_-_Turn_1'; Zh='巴哈姆特大迷宮 邂逅之章1'; Exp=$ARR; Type='raid'; PC=8; Lv=50; HE=$false},
    @{Id='binding_coil_of_bahamut_-_turn_2'; Page='The_Binding_Coil_of_Bahamut_-_Turn_2'; Zh='巴哈姆特大迷宮 邂逅之章2'; Exp=$ARR; Type='raid'; PC=8; Lv=50; HE=$false},
    @{Id='binding_coil_of_bahamut_-_turn_3'; Page='The_Binding_Coil_of_Bahamut_-_Turn_3'; Zh='巴哈姆特大迷宮 邂逅之章3'; Exp=$ARR; Type='raid'; PC=8; Lv=50; HE=$false},
    @{Id='binding_coil_of_bahamut_-_turn_4'; Page='The_Binding_Coil_of_Bahamut_-_Turn_4'; Zh='巴哈姆特大迷宮 邂逅之章4'; Exp=$ARR; Type='raid'; PC=8; Lv=50; HE=$false},
    @{Id='binding_coil_of_bahamut_-_turn_5'; Page='The_Binding_Coil_of_Bahamut_-_Turn_5'; Zh='巴哈姆特大迷宮 邂逅之章5'; Exp=$ARR; Type='raid'; PC=8; Lv=50; HE=$false},
    @{Id='second_coil_of_bahamut_-_turn_1'; Page='The_Second_Coil_of_Bahamut_-_Turn_1'; Zh='巴哈姆特大迷宮 侵略之章1'; Exp=$ARR; Type='raid'; PC=8; Lv=50; HE=$false},
    @{Id='second_coil_of_bahamut_-_turn_2'; Page='The_Second_Coil_of_Bahamut_-_Turn_2'; Zh='巴哈姆特大迷宮 侵略之章2'; Exp=$ARR; Type='raid'; PC=8; Lv=50; HE=$false},
    @{Id='second_coil_of_bahamut_-_turn_3'; Page='The_Second_Coil_of_Bahamut_-_Turn_3'; Zh='巴哈姆特大迷宮 侵略之章3'; Exp=$ARR; Type='raid'; PC=8; Lv=50; HE=$false},
    @{Id='second_coil_of_bahamut_-_turn_4'; Page='The_Second_Coil_of_Bahamut_-_Turn_4'; Zh='巴哈姆特大迷宮 侵略之章4'; Exp=$ARR; Type='raid'; PC=8; Lv=50; HE=$false},
    @{Id='second_coil_of_bahamut_savage_-_turn_1'; Page='The_Second_Coil_of_Bahamut_-_Turn_1'; Zh='巴哈姆特大迷宮 侵略之章1 (零式)'; Exp=$ARR; Type='raid'; PC=8; Lv=50; HE=$true},
    @{Id='second_coil_of_bahamut_savage_-_turn_2'; Page='The_Second_Coil_of_Bahamut_-_Turn_2'; Zh='巴哈姆特大迷宮 侵略之章2 (零式)'; Exp=$ARR; Type='raid'; PC=8; Lv=50; HE=$true},
    @{Id='second_coil_of_bahamut_savage_-_turn_3'; Page='The_Second_Coil_of_Bahamut_-_Turn_3'; Zh='巴哈姆特大迷宮 侵略之章3 (零式)'; Exp=$ARR; Type='raid'; PC=8; Lv=50; HE=$true},
    @{Id='second_coil_of_bahamut_savage_-_turn_4'; Page='The_Second_Coil_of_Bahamut_-_Turn_4'; Zh='巴哈姆特大迷宮 侵略之章4 (零式)'; Exp=$ARR; Type='raid'; PC=8; Lv=50; HE=$true},
    @{Id='final_coil_of_bahamut_-_turn_1'; Page='The_Final_Coil_of_Bahamut_-_Turn_1'; Zh='巴哈姆特大迷宮 真源之章1'; Exp=$ARR; Type='raid'; PC=8; Lv=50; HE=$false},
    @{Id='final_coil_of_bahamut_-_turn_2'; Page='The_Final_Coil_of_Bahamut_-_Turn_2'; Zh='巴哈姆特大迷宮 真源之章2'; Exp=$ARR; Type='raid'; PC=8; Lv=50; HE=$false},
    @{Id='final_coil_of_bahamut_-_turn_3'; Page='The_Final_Coil_of_Bahamut_-_Turn_3'; Zh='巴哈姆特大迷宮 真源之章3'; Exp=$ARR; Type='raid'; PC=8; Lv=50; HE=$false},
    @{Id='final_coil_of_bahamut_-_turn_4'; Page='The_Final_Coil_of_Bahamut_-_Turn_4'; Zh='巴哈姆特大迷宮 真源之章4'; Exp=$ARR; Type='raid'; PC=8; Lv=50; HE=$false},
    @{Id='labyrinth_of_the_ancients'; Page='The_Labyrinth_of_the_Ancients'; Zh='古之民迷宮'; Exp=$ARR; Type='alliance'; PC=24; Lv=50; HE=$false},
    @{Id='syrcus_tower'; Page='Syrcus_Tower'; Zh='席爾克斯塔'; Exp=$ARR; Type='alliance'; PC=24; Lv=50; HE=$false},
    @{Id='world_of_darkness'; Page='The_World_of_Darkness'; Zh='暗之世界'; Exp=$ARR; Type='alliance'; PC=24; Lv=50; HE=$false},
    # Late DT (only ones with CGW)
    @{Id='underkeep'; Page='The_Underkeep'; Zh='地下要塞'; Exp=$DT; Type='dungeon'; PC=4; Lv=100; HE=$false},
    @{Id='vanguard'; Page='Vanguard'; Zh='先鋒'; Exp=$DT; Type='dungeon'; PC=4; Lv=98; HE=$false},
    @{Id='mistwake'; Page='Mistwake'; Zh='霧之覺醒'; Exp=$DT; Type='dungeon'; PC=4; Lv=100; HE=$false},
    @{Id='unmaking'; Page='The_Unmaking'; Zh='解構'; Exp=$DT; Type='trial'; PC=8; Lv=100; HE=$false},
    @{Id='minstrels_ballad_sphenes_burden'; Page="The_Minstrel's_Ballad:_Sphene's_Burden"; Zh='絲菲妮絕嘆殲殛戰'; Exp=$DT; Type='trial'; PC=8; Lv=100; HE=$true},
    @{Id='jeuno_the_first_walk'; Page='Jeuno:_The_First_Walk'; Zh='朱諾：第一巡行'; Exp=$DT; Type='raid'; PC=24; Lv=100; HE=$false},
    @{Id='san_doria_the_second_walk'; Page="San_d'Oria:_The_Second_Walk"; Zh='桑多利亞：第二巡行'; Exp=$DT; Type='raid'; PC=24; Lv=100; HE=$false},
    @{Id='windurst_the_third_walk'; Page='Windurst:_The_Third_Walk'; Zh='溫達斯：第三巡行'; Exp=$DT; Type='raid'; PC=24; Lv=100; HE=$false},
    @{Id='aac_heavyweight_m1'; Page='AAC_Heavyweight_M1'; Zh='AAC 重量級 M1'; Exp=$DT; Type='raid'; PC=8; Lv=100; HE=$false}
)

$ok = 0; $fail = 0
foreach ($m in $manifest) {
    $r = Write-DutyFromCGW -DutyId $m.Id -CGWPage $m.Page -NameZh $m.Zh -Expansion $m.Exp -Type $m.Type -PC $m.PC -Lv $m.Lv -HighEnd $m.HE
    if ($r) { $ok++; Write-Host "[OK] $($m.Id)" } else { $fail++; Write-Host "[FAIL] $($m.Id)" }
}
Write-Host ""
Write-Host "Wrote $ok, failed $fail of $($manifest.Count)"
